export const crm = (name: string) => `http://www.cidoc-crm.org/cidoc-crm/${name}`
export const dcterms = (name: string) => `http://purl.org/dc/terms/${name}`
export const crmdig = (name: string) => `http://www.ics.forth.gr/isl/CRMdig/${name}`
export const frbroo = (name: string) => `http://iflastandards.info/ns/fr/frbr/frbroo/${name}`
export const nivers = (name: string) => `https://raw.githubusercontent.com/digimuwi/cadence-parfaite/main/ontologies/nivers1667.ttl#${name}`
export const crminf = (name: string) => `http://www.cidoc-crm.org/cidoc-crm/CRMinf/${name}`
export const midi = (name: string) => `http://purl.org/midi-ld/midi#${name}`
export const mer = (name: string) => `https://measuring-early-records.org/${name}`
export const oa = (name: string) => `http://www.w3.org/ns/oa#${name}`
export const rollo = (name: string) => `https://linked-rolls.org/roll-o/${name}`
